---
- name: Start yggdrasil
  ansible.builtin.service:
    name: yggdrasil
    enabled: true
    state: started
  when: ansible_facts["os_family"] in ["Debian", "RedHat", "Archlinux"]

# This separate entry here is needed because
# the service module does not support runit
- name: Start yggdrasil
  community.general.runit:
    name: yggdrasil
    enabled: true
    state: started
  when: ansible_facts["os_family"] in ["Void"]

# This separate entry here is needed because
# the service module does not support dinit
- name: Start yggdrasil
  ansible.builtin.command:
    argv:
      - /usr/bin/dinitctl
      - --system
      - enable
      - yggdrasil
    creates: /etc/dinit.d/boot.d/yggdrasil
  when: ansible_facts["os_family"] in ["Chimera"]
