---
- name: Import void linux tasks
  ansible.builtin.import_tasks: install/void.yml
  when: ansible_facts["os_family"] in ["Void"]

- name: Import fedora tasks
  ansible.builtin.import_tasks: install/fedora.yml
  when: ansible_facts["os_family"] in ["RedHat"]

- name: Import debian tasks
  ansible.builtin.import_tasks: install/debian.yml
  when: ansible_facts["os_family"] in ["Debian"]

- name: Import arch tasks
  ansible.builtin.import_tasks: install/arch.yml
  when: ansible_facts["os_family"] in ["Archlinux"]

- name: Import chimera tasks
  ansible.builtin.import_tasks: install/chimera.yml
  when: ansible_facts["os_family"] in ["Chimera"]

# TODO: Support more distros (and maybe even Windows one day)
